### ISSUE TITLE
cljfmt should check source and test files

### ISSUE THREAD

**Issue by drassaby** [amperity/gocd-vault-secrets#15]
Right now, if you run `lein cljfmt check`, it only checks source files. Given our CI runs style checks over tests as well (and that tests should be well formatted anyway), we should configure this project to check both with `lein cljfmt check`

**Comment by drewinglis** [comment]
We should also be using `cljstyle` instead of `cljfmt`. >.>

**Comment by drewinglis** [comment]
Created https://github.com/amperity/gocd-vault-secrets/issues/16 to track this.
